### ISSUE TITLE
刚接触后发现的两个不便之处

### ISSUE THREAD

**Issue by wanjj** [nokitjs/nokit#2]
1. nokit start -watch 貌似并没有作用，当我修改homeController和home.html时，都没有自动刷新页面。
2. 在package.json的dependencies中相关依赖项没有。虽然我直接用命令行运行没有问题，但是当我使用visual studio code自带的调试时就会报错：module not found。 我觉得一些基础依赖应该要存在吧，不然我还得一个一个去添加么，这样很不方便耶~  我也不知道你到底有哪些依赖啊……像express   直接npm install就可以把相关依赖安装完毕，我觉得也可以做成这样子。

一点点肤浅的使用感受。
(windows7 + visual studio code+ chorme最新)

**Comment by Houfeng** [comment]
@wanjj  非常感谢您的反馈
1. -watch 不会刷新页面，而是在指定的文件发生变化时会自动重启进程。
2. 应该是 app.js 中的对 nokitjs 的依赖没有找到，因为 nokit start 命令启动应用时会忽略 app.js 所以不会报错，而直接运行则需要，目前版本的“应用模板”，可以设置 NODE_PATH 环境变量，或在当前目录 npm install nokitjs。 ```这个问题会在本周的新版本中修复```

**Comment by wanjj** [comment]
@Houfeng thanks for your response .

**Comment by Houfeng** [comment]
@wanjj 
第二个问题已经修复，查看更新 [https://github.com/nokitjs/nokit/releases/tag/1.15.1](https://github.com/nokitjs/nokit/releases/tag/1.15.1)
